name: Build

on:
  workflow_call:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/cache@v3
        with:
          path: |
            ~/.nuget/packages
            !~/.nuget/packages/unwanted
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json

      - name: Install dependencies
        run: dotnet restore --locked-mode

      - name: Build
        run: dotnet build -c Release --no-restore
      
      - name: Test
        run: dotnet test -c Release --no-restore --collect:"XPlat Code Coverage" --logger "trx;LogFilePrefix=TestResults" -r TestResults -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

      - name: upload TestResults
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            ./TestResults/*.trx
            ./TestResults/**/coverage.opencover.xml
            
      - name: Prepare artifact for transfer
        run: |
          # Save ENV needed for actions in secure workflow
          echo "PR_HEADSHA=${{ github.event.pull_request.head.sha }}" >> pr.env
          echo "PR_NUMBER=${{ github.event.pull_request.number }}"    >> pr.env
          echo "PR_TITLE=${{ github.event.pull_request.title }}"      >> pr.env
          echo "BUILD_DIR=${{ env.BUILD_DIR }}"                       >> pr.env

          tar --zstd -cf artifact.tar.zst pr.env ${{ env.BUILD_DIR }}

      - name: Upload artifact for workflow transfer
        uses: actions/upload-artifact@v3
        with:
          name: preview-build
          path: artifact.tar.zst
          retention-days: 1
