name: Workflow Run Manager

on:
  push:
  pull_request:
    branches:
      - main
        develop
    
jobs:
  first:
    name: pretend the First workflow
    uses: kirbyAlasdairAnswer/AnswerKing-CS/.github/workflows/build-and-test.yml@main

  second:
    name: pretend the Second workflow
    needs: first
    if: github.event_name == 'pull_request'
    uses: kirbyAlasdairAnswer/AnswerKing-CS/.github/workflows/report-and-analyze.yml@main
    secrets: inherit
