name: manage workflows

on:
  push:
  pull_request:
    branches:
      - main
      - develop
    
jobs:
  first:
    name: pretend the First workflow
    uses: ./.github/workflows/build-and-test.yml

  second:
    name: pretend the Second workflow
    needs: first
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/report-and-analyze.yml
    secrets: inherit
