name: manage workflows

on:
  push:
  pull_request:
    branches:
      - main
      - develop
    
jobs:
  pull-request:
    name: test, report and anlayse
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/build-and-test.yml
    secrets: inherit
