name: pull request

on:
  push:
  pull_request:
    
jobs:
  first:
      name: pretend the First workflow
      uses: kirbyAlasdairAnswer/AnswerKing-CS/.github/workflows/build-and-test.yml@main

  second:
      name: pretend the Second workflow
      needs: first
      uses: kirbyAlasdairAnswer/AnswerKing-CS/.github/workflows/report-and-analyze.yml@main
