name: Build Docker

on:
  workflow_run:
    workflows: ["Test", "Static Analysisa"]
    types:
      - completed
jobs:
  push-to-registry:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v3
